<a href="https://colab.research.google.com/github/kendala545-dot/mis433/blob/main/Aaron_Kendall_python_basics_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Aaron
Welcome, Aaron!


In [ ]:
# complete your program here
f_str = input('Please enter the temperature in Fahrenheit: ')
f = float(f_str)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')

Please enter the temperature in Fahrenheit: 80
80.0F is 26.666666666666668 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c_str = input('Please enter the temperature in Celsius: ')
c = float(c_str)

# Fahrenheit = (Celsius * 9/5) + 32
f = (c * 9/5) + 32

print(f'{c}C is {f} in Fahrenheit.')

Please enter the temperature in Celsius: 60
60.0C is 140.0 in Fahrenheit.


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d_str = input('Please enter the temperature: ')
d = float(d_str)
m = input('Is this in Celsius or Fahrenheit? ').upper()

if m == 'C':
    # Convert Celsius to Fahrenheit
    f = (d * 9/5) + 32
    print(f'{d}C is {f} in Fahrenheit')
elif m == 'F':
    # Convert Fahrenheit to Celsius
    c = (d - 32) * 5/9
    print(f'{d}F is {c} in Celsius')
else:
    print('Invalid unit. Please enter C or F.')

Please enter the temperature: 60
Is this in Celsius or Fahrenheit? c
60.0C is 140.0 in Fahrenheit


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
print(len(sentence))

48


In [ ]:
# Convert the whole string to lower case.
sentence.lower()

'talk is cheap. show me the code - linus torvalds'

In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
# 10th character from left is at index 9 (since 0-based indexing)
# 10th character from right means up to index len(sentence) - 10
# For slicing, the end index is exclusive, so we use len(sentence) - 10 + 1
substring = sentence[9 : len(sentence) - 9]
print(substring)

heap. Show me the code - Linus


In [ ]:
# Split the sentence into a list of substrings by space ' '.
words = sentence.split(' ')
print(words)

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without punctuations).
import string

# Create a translation table to remove punctuation
translator = str.maketrans('', '', string.punctuation)

# Remove punctuation and convert to lowercase, then split into words
cleaned_words = sentence.translate(translator).lower().split()

print(cleaned_words)

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
vowels = 'aeiou'
count = 0
for v in vowels:
    #print(v)
    print(v, sentence.lower().count(v))
    count += sentence.lower().count(v)
print(f"The total number of characters is {count}")

a 3
e 4
i 2
o 3
u 1
The total number of characters is 13


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
vowels = 'aeiouAEIOU'
vowel_positions = []
for i in range(len(sentence)):
    if sentence[i] in vowels:
        vowel_positions.append(i)
print(vowel_positions)

[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
    cubes.append(i**3)
print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
cubes_lc = [i**3 for i in range(5)]
print(cubes_lc)

[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = 'aeiouAEIOU'

# Your list comprehension goes here. Make sure to print the result!
vowel_positions_lc = [index for index, char in enumerate(sentence) if char in vowels]
print(vowel_positions_lc)

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')

# add your code here

n = int(n)

if n ==1:
  firbonacci = [0]
elif n ==2:
  fibonacci = [0 ,1]
elif n > 2:
    fibonacci = [0, 1]
    while len(fibonacci) < n:
      fibonacci.append(fibonacci[-1] + fibonacci[-2])
print(fibonacci)


How many numbers do you want? 8
[0, 1, 1, 2, 3, 5, 8, 13]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66
}

In [34]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(f'{v}: {v_dict[v] * 100}% efficacy')

Which vaccine? Pfizer
Pfizer: 95.0% efficacy


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66,
    'Sputnik V': 0.914
}

In [35]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66,
    'Sputnik V': 0.914,
    'Sinovac': 0.5038
}

In [36]:
# Print vaccines with efficacy lower than 90%.
print('Vaccines with efficacy lower than 90%:')
for vaccine, efficacy in v_dict.items():
    if efficacy < 0.90:
        print(f'{vaccine}: {efficacy * 100}% efficacy')

Vaccines with efficacy lower than 90%:
AstraZeneca: 72.0% efficacy
Johnson & Johnson: 66.0% efficacy
Sinovac: 50.38% efficacy


In [37]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [39]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for char in sentence:
    if char.isalpha(): # Check if the character is an alphabet
        char_lower = char.lower() # Convert to lowercase to treat 'A' and 'a' as the same
        ch_dict[char_lower] = ch_dict.get(char_lower, 0) + 1


# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [41]:
import numpy as np

In [47]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
even_numbers = np.arange(2, 41, 2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [48]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
odd_numbers = np.arange(1, 40, 2)
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [50]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
M_pattern = np.arange(100).reshape(10, 10)
print(M_pattern)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [61]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(loc=0, scale=1, size=(10, 10))
print(M)

[[ 0.49675496  0.40556958 -1.2988266   0.92244986 -0.79379741 -1.35905384
  -0.87865573  0.20762586  0.52091754 -0.82943206]
 [-1.10533237  1.65552343 -3.04813448  0.09262254 -1.03551511 -0.23565449
   0.32344748 -1.17435805  1.01082377 -0.01571045]
 [-1.24772284 -0.341585    0.46960374 -2.04653579 -0.02927558 -0.38984102
  -0.93639477 -1.79260439 -0.69484084 -0.32038218]
 [ 2.83908425  0.50181961 -0.51949283 -1.35092003 -0.03819098 -0.3088692
   0.61180115 -0.29622506 -0.50705998  0.0936075 ]
 [ 1.08310971 -0.24884328 -0.35994561  0.03743135  0.36839184 -0.34812096
  -1.92511296 -1.12590422  0.84459951  0.35112575]
 [-0.64396532 -0.43221146 -1.05364438 -1.19688461 -1.62958509 -0.25367536
   1.69134243 -0.82607419  0.15914959 -0.15423438]
 [-0.96167021  0.52894189  2.40457998  0.36656906  0.64216865  0.19006853
  -0.64381101 -0.20418217 -1.10611644  1.8411021 ]
 [-0.60007521 -0.94444195 -2.50800062  0.15920646 -2.42064245 -0.25882216
  -0.35262953  0.03825453 -0.81927137 -0.7678028 ]
 

In [63]:
num_greater_than_1 = np.sum(np.abs(M) > 1)
print(f"Number of elements in M with absolute value greater than 1: {num_greater_than_1}")

Number of elements in M with absolute value greater than 1: 33


In [66]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of columns (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().

# Convert r and c to integers
r = int(r)
c = int(c)

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(low=10, high=20, size=(r, c))
arr

Row count: 5
column count: 5


array([[17, 18, 19, 15, 11],
       [19, 11, 14, 10, 11],
       [11, 10, 19, 11, 11],
       [18, 15, 15, 19, 11],
       [18, 14, 15, 12, 17]])

In [68]:
# output the element in the first row and the third column
print(arr[0, 2])

19


In [69]:
# output the element in the second row and the last column
print(arr[1, -1])

11


In [70]:
# output the second row of the array
print(arr[1, :])

[19 11 14 10 11]


In [71]:
# output the second last row of the array
print(arr[-2, :])

[18 15 15 19 11]


In [72]:
# output the second column of the array
print(arr[:, 1])

[18 11 10 15 14]


In [73]:
# output the second last column of the array
print(arr[:, -2])

[15 10 11 19 12]


In [74]:
# output the upper-left 3x3 sub-array
print(arr[0:3, 0:3])

[[17 18 19]
 [19 11 14]
 [11 10 19]]


In [75]:
# output the bottom-left 3x3 sub-array
print(arr[-3:, :3])

[[11 10 19]
 [18 15 15]
 [18 14 15]]


In [78]:
# output the bottom-right 3x3 sub-array
print(arr[-3:, -3:])

[[19 11 11]
 [15 19 11]
 [15 12 17]]


In [79]:
# Create a 1-D array from 1 to 50 (inclusive)

# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]


A = np.arange(1, 51)
A = A.reshape(5, 10)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [80]:
# add a row [51,...,60] to A
new_row = np.arange(51, 61)
A = np.vstack((A, new_row))
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [81]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.vsplit(A, 2)
print("A1:")
print(A1)
print("\nA2:")
print(A2)

A1:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

A2:
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [93]:
# Add 10 to each element of A
new_row = np.arange(31, 41)
A1 = np.vstack((A, new_row))
print("A1:")
print(A1)

new_row = np.arange(61, 71)
A2 = np.vstack((A, new_row))
print("\nA2:")
print(A2)

A1:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [31 32 33 34 35 36 37 38 39 40]]

A2:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [94]:
# Redefine A1 to be the row [31-40] from A_plus_10
A1 = A_plus_10[2, :]

# Redefine A2 to be the row [61-70] from A_plus_10
A2 = A_plus_10[5, :]

print("New A1:")
print(A1)
print("\nNew A2:")
print(A2)

New A1:
[31 32 33 34 35 36 37 38 39 40]

New A2:
[61 62 63 64 65 66 67 68 69 70]


In [110]:
# Calculate the square root of each element in A
A1_sqrt = np.sqrt(A1)
print("Square root of A1:")
print(A1_sqrt)

A2_sqrt = np.sqrt(A2)
print("Square root of A2:")
print(A2_sqrt)

Square root of A1:
[5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
 6.08276253 6.164414   6.244998   6.32455532]
Square root of A2:
[7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
 8.18535277 8.24621125 8.30662386 8.36660027]


In [111]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [112]:
# Print the mean, standard devietion of all numbers in M
print(f"Mean of M: {np.mean(M)}")
print(f"Standard deviation of M: {np.std(M)}")

Mean of M: -0.27857501515885075
Standard deviation of M: 1.0192302533254338


In [105]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
maximum = np.max(M)
q3 = np.percentile(M, 75)
median = np.median(M)
q1 = np.percentile(M, 25)
minimum = np.min(M)

print(f"Maximum of M: {maximum}")
print(f"3rd Quartile (Q3) of M: {q3}")
print(f"Median of M: {median}")
print(f"1st Quartile (Q1) of M: {q1}")
print(f"Minimum of M: {minimum}")

Maximum of M: 2.8390842456351133
3rd Quartile (Q3) of M: 0.33036704733961564
Median of M: -0.2775236100111834
1st Quartile (Q1) of M: -0.948749011494066
Minimum of M: -3.048134480762875
